foodonline_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from marketplace import views as MarketplaceViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('accounts.urls')),
    path('marketplace/', include('marketplace.urls')),

    #cart path
    path('cart/', MarketplaceViews.cart, name='cart'),

    # search path
    path('search/', MarketplaceViews.search, name='search'),

    #checkout path
    path('checkout/', MarketplaceViews.checkout , name='checkout'),

    #order path
    path('order/', include('order.urls')),



]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('place_order/', views.place_order, name='place_order')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point

#class untuk model user manager
class UserManager(BaseUserManager):
  def create_user(self, first_name, last_name, username, email, password):
    if not email:
      raise ValueError('Email tidak boleh kosong!')

    if not username:
      raise ValueError('Username tidak boleh kosong!')

    user = self.model(
      email = self.normalize_email(email),
      username = username,
      first_name = first_name,
      last_name = last_name,
    )
    user.set_password(password)

    user.save(using=self._db)
    return user

  def create_superuser(self, first_name, last_name, username, email, password):
    user = self.create_user(
      email = email,
      username = username,
      password = password,
      first_name = first_name,
      last_name = last_name,
    )
    user.is_admin = True
    user.is_active = True
    user.is_staff = True
    user.is_superadmin = True

    user.save(using=self._db)
    return user


class User(AbstractBaseUser):
  VENDOR = 1
  CUSTOMER = 2

  ROLE_CHOICE = (
    (VENDOR, 'Vendor'),
    (CUSTOMER, 'Customer'),
  )

  first_name = models.CharField(max_length=50)
  last_name = models.CharField(max_length=50)
  username = models.CharField(max_length=50, unique=True)
  email = models.EmailField(max_length=100, unique=True)
  phone_number = models.CharField(max_length=12, blank=True)
  role = models.SmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)

  #required fields
  date_joined = models.DateTimeField(auto_now_add=True)
  last_login = models.DateTimeField(auto_now_add=True)
  created_date = models.DateTimeField(auto_now_add=True)
  modified_date = models.DateTimeField(auto_now=True)
  is_admin = models.BooleanField(default=False)
  is_active = models.BooleanField(default=False)
  is_staff = models.BooleanField(default=False)
  is_superadmin = models.BooleanField(default=False)


  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

  objects = UserManager()

  def __str__(self):
    return self.email

  def has_perm(self, perm, obj=None):
    return self.is_admin

  def has_module_perms(self, app_label):
    return True

  def get_role(self):
    if self.role == 1:
      user_role = 'Vendor'
    elif self.role == 2:
      user_role = 'Restaurant'
    return user_role

#model untuk user profile
class UserProfile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE, blank = True, null=True)
  profile_picture = models.ImageField(upload_to = 'user/profile_picture', blank=True, null=True)
  cover_photo = models.ImageField(upload_to = 'user/cover_photo', blank=True, null=True)
  address = models.CharField(max_length=250, blank=True,null=True)
  country = models.CharField(max_length=25, blank=True,null=True)
  state = models.CharField(max_length=25, blank=True,null=True)
  city = models.CharField(max_length=25, blank=True,null=True)
  pin_code = models.CharField(max_length=15, blank=True,null=True)
  latitude = models.CharField(max_length=20, blank=True,null=True)
  longitude = models.CharField(max_length=20, blank=True,null=True)
  location = gismodels.PointField(blank=True, null=True, srid=4326)
  created_at = models.DateTimeField(auto_now_add=True)
  modified_at = models.DateTimeField(auto_now=True)


  def __str__(self):
    return self.user.email

  def save(self, *args, **kwargs):
    if self.longitude and self.latitude:
      self.location = Point(float(self.longitude), float(self.latitude))
      return super(UserProfile, self).save(*args, **kwargs)
    return super(UserProfile, self).save(*args, **kwargs)

order/models.py
from django.db import models
from accounts.models import User
from menu.models import FoodItem

# Create your models here.
class Payment(models.Model):
  PAYMENT_METHOD = (
    ('Paypal', 'Paypal'),
    ('Transfer', 'Transfer'),
  )

  user = models.ForeignKey(User, on_delete=models.CASCADE)
  transaction_id = models.CharField(max_length=100)
  payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100)
  amount = models.CharField(max_length=10)
  status = models.CharField(max_length=100)
  create_at = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.transaction_id


class Order(models.Model):
  STATUS = (
    ('New', 'New'),
    ('Accepted', 'Accepted'),
    ('Complated', 'Complated'),
    ('Canceled', 'Canceled'),
  )

  user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
  payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank = True, null=True)
  order_no = models.CharField(max_length=20)
  first_name = models.CharField(max_length=50)
  last_name = models.CharField(max_length=50)
  phone = models.CharField(max_length=15, blank=True)
  email = models.EmailField(max_length=50)
  address = models.CharField(max_length=200)
  country = models.CharField(max_length=15, blank=True)
  state = models.CharField(max_length=15, blank=True)
  city = models.CharField(max_length=50)
  pin_code = models.CharField(max_length=10)
  total = models.FloatField()
  tax_data = models.JSONField(blank=True, help_text="Data Format: {'tax_type':{'tax_percentage' :'amount'}}")
  total_tax = models.FloatField()
  payment_method = models.CharField(max_length=20)
  status = models.CharField(max_length=15, choices=STATUS, default='New')
  is_ordered = models.BooleanField(default=False)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  @property
  def name(self):
    return f'(self.first_name)(self.last_name)'

  def __str__(self):
    return self.order_no


class OrderedFood(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  order = models.ForeignKey(Order, on_delete=models.CASCADE)
  payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
  fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
  quantity = models.IntegerField()
  price = models.FloatField()
  amount = models.FloatField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.fooditem.food_title

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FoodOnline</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->

	<link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="{% static 'css/bootstrap-slider.css' %}" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'css/custom.css' %}">

	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/modernizr.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>

	<!--google api scripts attach in header-->
 {% if '/' == request.path or '/profile/' in request.path %}
	<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" defer></script>
 {% endif %}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> <!-- sweet allert message js-->
<script src="{% static 'js/custom.js' %}" ></script>
<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>

	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>
</head>

<body>

{% comment %} Navbar Section {% endcomment %}
{% include 'include/navbar.html' %}

{% comment %} Main Contents Section {% endcomment %}
{% block content %}

{% endblock %}

{% comment %} Footer Section {% endcomment %}
{% include 'include/footer.html' %}

templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
		<!-- Main Section Start -->
		<div class="main-section">
			<!-- Home Pages Elements Strat -->
			<!-- Main Search Start -->
			<div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static 'extra-images/bg-image1.jpg' %}) no-repeat center / cover;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="element-title">
								<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
									We are in the business of food<br>our restaurants do</h1>
								<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
									Ridiculus sociosqu
									cursus neque cursus curae ante scelerisque vehicula.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="main-search fancy bg-holder">
								<!--FORM Pencarian-->
								<form action="{% url 'search' %}" method="GET">
									<div class="row">
										<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
											<div class="field-holder">
												<input type="text"  name="keyword" placeholder="Cari Resturant / Menu">
											</div>
										</div>
										<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
											<div class="field-holder">
												<ul>
													<li class="select-location">
														<div class="foodbakery-locations-fields-group foodbakery-focus-out">
															<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
															<input type="text" name="address" id="id_address" class="location-field-text filter" placeholder="Semua Lokasi">
															<input type="hidden" value="" name="lat" id="id_latitude" >
															<input type="hidden" value="" name="lng" id="id_longitude" >
														</div>
													</li>

												</ul>
											</div>
										</div>

										<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
											<div class="field-holder">
												<select name="radius" id="radius" style="height:50px;" required>
													<option value="" selected>Select Radius</option>
													<option value="1">1km</option>
													<option value="10">10km</option>
													<option value="15">15km</option>
													<option value="20">20km</option>
												</select>
											</div>
										</div>

										<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
											<div class="field-holder">
												<input type="submit" value="Cari">
											</div>
										</div>

									</div>
								</form>
							</div>
						</div>

					</div>
				</div>
			</div>
			<!-- Main Search End -->

			<!-- Top Restarurants Section Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-left">
								<h2>Top Restaurants</h2>
								<p>Explore restaurants, bars, and cafés by locality</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 " style="padding-right: 0 !important; padding-left: 0 !important">
							<div class="company-logo">
								<ul>
									{% for vendor in vendors %}
									<li class="has-border">
										<figure>
											{% if vendor.user_profile.profile_picture %}
											<a href="{% url 'vendor_detail' vendor.vendor_slug %}"><img src="{{vendor.user_profile.profile_picture.url }}" class="attachment-full size-full wp-post-image" alt=""></a>

											{% else %}
											<a href="#"><img src="{% static 'images/default-profile.png' %}" class="attachment-full size-full wp-post-image" alt=""></a>
											{% endif %}
										</figure>
									</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Top Restarurants Section End -->
			<!-- Choose From Most Popular Listin Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-center">
								<h2>Choose From Most Popular Restaurants</h2>
								<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="listing fancy">
								<ul class="row">
									{% for vendor in vendors %}
									<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
										<div class="list-post featured">
											<div class="img-holder">
												<figure>
													<a href="{% url 'vendor_detail' vendor.vendor_slug %}">
													{% if vendor.user_profile.profile_picture %}
														<img src="{{vendor.user_profile.profile_picture.url}}" class="img-thumb wp-post-image" alt=""></a>

													{% else %}
													<img src="{% static 'images/default-profile.png' %}" class="img-thumb wp-post-image" alt=""></a>
													{% endif %}


												</figure>
												{% if vendor.is_open %}
												<span class="restaurant-status open">
													<em class="bookmarkRibbon"></em>Open
												</span>
												{% else %}
												<span class="restaurant-status close">
													<em class="bookmarkRibbon"></em>Closed
												</span>
												{%endif%}
											</div>
											<div class="text-holder">
												<div class="list-rating">
													<div class="rating-star">
														<span class="rating-box" style="width: 100%;"></span>
													</div>
													<span class="reviews">(1)</span>
												</div>
												<div class="post-title">
													<h5>
														<a href="{% url 'vendor_detail' vendor.vendor_slug %}">{{vendor.vendor_name}}</a>

													</h5>
												</div>
												{% if vendor.user_profile.city and vendor.user_profile.state %}
													<span>{{vendor.user_profile.city}},{{vendor.user_profile.state}}</span>
												{% endif %}

												{% if vendor.user_profile.address %}
												<br>
												<span><small><b>{{vendor.kms}}km</b></small></span>
													{% endif %}

											</div>

										</div>
									</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Choose From Most Popular Listing End -->

			<!-- Home Pages Elements End  -->
		</div>
		<!-- Main Section End -->
	{% endblock %}